apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: tictactoe
data:
  database-name: "tictactoe_game"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: tictactoe
type: Opaque
data:
  username: dGljdGFjdG9lX3VzZXI=  # base64 encoded
  password: aGlhYmRqYWRqYjU2NjYzbmFoYWg=  # base64 encoded

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: tictactoe
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3RpY3RhY3RvZV91c2VyOmhpYWJkamFkamI1NjY2M25haGFoQHBvc3RncmVzLXNlcnZpY2U6NTQzMi90aWN0YWN0b2VfZ2FtZQ==
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==